server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost/db_spring_security_token
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api