server:
  port: 8898
spring:
  datasource:
    druid:
      # JDBC 配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_druid_spring_boot_starter?useUnicode=true&characterEncoding=utf-8
      username: root
      password: weilai09290013
      # 连接池配置
      # 监控配置
      stat-view-servlet:
        enabled: true
